In [41]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestRegressor

In [43]:
# load data in
water_data_path = r'C:\Users\Paul\OneDrive - University of Exeter\Machine Learning Summer Code\Classical\water_potability.csv'
water_data = pd.read_csv(water_data_path)

# set X and y
water_data.dropna(axis=0, subset=['Potability'], inplace=True)
y = water_data.Potability
water_data.drop(['Potability'], axis=1, inplace=True)
X = water_data.select_dtypes(exclude=['object'])

X_train, X_valid, y_train, y_valid = train_test_split(X, y, random_state=0, train_size=0.8, test_size=0.2)

# data has some null values so using imputation to assign average values

my_imputer = SimpleImputer()
imputed_X_train = pd.DataFrame(my_imputer.fit_transform(X_train))
imputed_X_valid = pd.DataFrame(my_imputer.transform(X_valid))

imputed_X_train.columns = X_train.columns
imputed_X_train.columns = X_valid.columns

final_X_train = imputed_X_train
final_X_valid = imputed_X_valid

pota_model = RandomForestRegressor(n_estimators=100, random_state=0)
pota_model.fit(final_X_train, y_train)
pota_preds = pota_model.predict(final_X_valid)
print(mean_absolute_error(y_valid, pota_preds))

0.41547256097560975

In [47]:
final_X_train.describe()

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity
count,2620.000000,2620.000000,2620.000000,2620.000000,2620.000000,2620.000000,2620.000000,2620.000000,2620.000000
mean,7.080687,196.965955,21923.294241,7.114879,333.395374,424.916791,14.305207,66.523639,3.973622
std,1.462605,32.674915,8739.962195,1.611971,36.283249,80.883734,3.328554,15.776613,0.776219
min,0.000000,73.492234,320.942611,0.352000,129.000000,181.483754,2.200000,8.577013,1.450000
25%,6.284835,177.091694,15508.895243,6.108402,316.549961,364.656609,12.060510,56.945270,3.463014
50%,7.080687,197.281785,20882.160702,7.117378,333.395374,420.363840,14.247815,66.523639,3.957630
75%,7.846159,217.369206,27194.313643,8.106119,350.070579,480.087471,16.581983,77.033445,4.497655
max,14.000000,323.124000,56867.859236,13.127000,481.030642,753.342620,28.300000,124.000000,6.739000